### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by Yulia-K-1** [StrawberryMaster/wayback-machine-downloader#25]
Hello!
Before downloading, the program writes: 185653 files found matching criteria.
After downloading, I check and see that not everything has been downloaded.
I'll try to download it again with the same command
I get the following:
Found 180751 previously downloaded files, skipping them.
4902 files to download:
2025-07-25 09:59:46 [ERROR] Error processing file ...examlesite... invalid byte sequence in UTF-8
(for all 4902 files)
How can I download the remaining files?

**Comment by Yulia-K-1** [comment]
Thanks, but this code didn't help (to my regret)...

**Comment by StrawberryMaster** [comment]
Odd. I'll take a closer look at this then

**Comment by Yulia-K-1** [comment]
It seems I did everything as it says there. It still didn't help to solve the problem. There were lines in the main file that I didn't have (355-363). I tried with them and without them. Still an error. Should I have canceled yesterday's correction first? Is it possible to save files despite the error? What problems could this cause? Thank you for trying to solve this.

**Comment by StrawberryMaster** [comment]
Sorry for the delay here. Can you show me examples of files it didn't download, if possible? Starting to think these may have a character that is considered 'invalid' by the downloader, meaning I was looking at something completely different.

**Comment by Yulia-K-1** [comment]
Yes, here are some examples of errors:
_2025-07-29 11:39:51 [ERROR] Error processing file http://bards.ru/persons.php?ch=%C5: invalid byte sequence in UTF-8
2025-07-29 11:39:51 [ERROR] Error processing file http://bards.ru/archives/index.php?ch=%CE: invalid byte sequence in UTF-8
2025-07-29 11:39:51 [ERROR] Error processing file http://bards.ru/persons.php?ch=%FC: invalid byte sequence in UTF-8
2025-07-29 11:39:51 [ERROR] Error processing file http://bards.ru/archives/index.php?ch=%CF: invalid byte sequence in UTF-8
2025-07-29 11:39:52 [ERROR] Error processing file http://bards.ru/persons.php?ch=%D1: invalid byte sequence in UTF-8
2025-07-29 11:39:52 [ERROR] Error processing file http://bards.ru/collectives/index.php?type=8&&ch=%D3: invalid byte sequence in UTF-8
2025-07-29 11:39:52 [ERROR] Error processing file http://bards.ru/collectives/index.php?type=8&&ch=%CE: invalid byte sequence in UTF-8
2025-07-29 11:39:52 [ERROR] Error processing file http://bards.ru/collectives/index.php?type=8&&ch=%C4: invalid byte sequence in UTF-8
2025-07-29 11:39:53 [ERROR] Error processing file http://bards.ru/collectives/index.php?type=8&&ch=%D8: invalid byte sequence in UTF-8
2025-07-29 11:39:53 [ERROR] Error processing file http://bards.ru/collectives/index.php?type=8&&ch=%D2: invalid byte sequence in UTF-8_
I'm also surprised that there are so few pages.
Loading from the original site shows over 14 million files.
Is it really possible that the web archive indexes such a small part of the site?

**Comment by StrawberryMaster** [comment]
Hm, maybe. It's also possible a bunch of them are redirects or duplicates, so it's hard for me to guess. It depends a lot on the site.

Looking at this, I think the issue is with `tidy_bytes` after all.

**Comment by adampweb** [comment]
Wouldn't GitLab's encoding_helper be worth a try?
[https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/encoding_helper.rb?ref_type=heads](https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/encoding_helper.rb?ref_type=heads)

**Comment by StrawberryMaster** [comment]
Alright, I believe it should be working now - I can download the . If you wanna test this, just replace the content in `tidy_bytes.rb` with the current version in the repo, and same for `wayback_machine_downloader.rb`. Eventually I'll have to work on a proper fix, but this worked here

**Comment by Yulia-K-1** [comment]
Nothing works for me at all, even things that used to work.
Endless list of errors.
_**Sample:**
^ unexpected ',', expecting end-of-input
> 1951 | <div id="LC2" class="react-code-text react-code-li ... 
| ^ unexpected '<'; expected a `)` to close the arguments 
| ^ unexpected '<'; expected an argument 
| ^~ unexpected local variable or method, expecting end-of-input 
| ^~~~~ unexpected constant path after `class`; class/module name must be CONSTANT 
| ^~~~~ unexpected constant path after `class`; class/module name must be CONSTANT 
| ^~~~~ unexpected constant path after `class`; class/module name must be CONSTANT 
| ^~~~~ unexpected 'class', expecting end-of-input 
| ^ unexpected '=', ignoring it
> 1952 | </div> 
| ^ unexpected '<'; expected an expression after the operator
> 1953 | ... /span> <span class=pl-s>&#39;thread&#39;</span></div>_

**Comment by Yulia-K-1** [comment]
Some files were downloaded with the new version. Thank you!
The rest of the files give the following error:

_Found 183548 previously downloaded files, skipping them.
1997 files to download:
Failed: http://www.bards.ru/archives/part.php?id=5586%3Cbr%20/%3E # No such file or directory @ dir_s_mkdir - C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/bin/websites/bards.ru/archives/part.php%3Fid%3D5586%3Cbr /%3E (2/1997)
Failed: http://www.bards.ru/archives/part.php?id=3054%3Cbr%20/%3E # No such file or directory @ dir_s_mkdir - C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/bin/websites/bards.ru/archives/part.php%3Fid%3D3054%3Cbr /%3E (3/1997)
Failed: http://www.bards.ru/archives/part.php?id=5458%3Cbr%20/%3E # No such file or directory @ dir_s_mkdir - C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/bin/websites/bards.ru/archives/part.php%3Fid%3D5458%3Cbr /%3E (4/1997)_

**Comment by StrawberryMaster** [comment]
Oh yeah, looks like some of the links have HTML tags in them (like `<br/>`) which causes it to fail. I'll have to push out 2.4.1 tomorrow with this fix, but I was able to download the files here with the latest commit

**Comment by Yulia-K-1** [comment]
I tried using commit 6ad312f
I got this error:
_C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/lib/wayback_machine_downloader.rb:374:in 'String#gsub!': invalid byte sequence in UTF-8 (ArgumentError)

      file_id.gsub!(/<[^>]*>/, '') # sanitize HTML tags
                    ^^^^^^^^^^^^^
        from C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/lib/wayback_machine_downloader.rb:374:in 'block in WaybackMachineDownloader#get_file_list_curated'
        from C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/lib/wayback_machine_downloader.rb:370:in 'Array#each'
        from C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/lib/wayback_machine_downloader.rb:370:in 'WaybackMachineDownloader#get_file_list_curated'
        from C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/lib/wayback_machine_downloader.rb:735:in 'WaybackMachineDownloader#file_list_by_timestamp'
        from C:/Users/USER/.local/share/gem/ruby/3.4.0/gems/wayback_machine_downloader_straw-2.4.0/lib/wayback_machine_downloader.rb:525:in 'WaybackMachineDownloader#download_files'
        from wayback_machine_downloader:96:in '<main>'_

**Comment by StrawberryMaster** [comment]
Sorry for the late response. Not sure why this fails to load on your end, but I did a cleanup there and just pushed 2.4.1 - which should let some of these files load, at least. (I have no idea how many more are broken, but at least this gets some links out of the way!)

**Comment by PQCraft** [comment]
Currently having this error while trying to download some old windows docs
```
$ wayback_machine_downloader --recursive-subdomains --local -f 20010401 -t 20010501 'http://msdn.microsoft.com/library/psdk/portals/win32start_1n6t.htm'

...

Processing downloads:
[FAILED]  http://msdn.microsoft.com:80/library/psdk/portals/win32start_1n6t.htm # invalid byte sequence in UTF-8 (1/1)

...
```

**Comment by PQCraft** [comment]
Narrowed it down to this line in the file
```
<P>The Microsoft® Win32® application programming interface (API) provides building blocks used by applications written for Microsoft Windows NT®, Windows®&nbsp;2000, and Windows&nbsp;95/98. You can provide your application with a graphical user interface; display graphics and formatted text; and manage system objects such as memory, files, and processes.</P>
```
Did a hexdump and the HTML file uses `AE` instead of the UTF-8 `C2 AE` for the `®` symbol, so I'm guessing the page is encoded using Windows-1252

**Comment by PQCraft** [comment]
I tried digging into the code to figure out which parts to change, but I'm not well-versed in ruby, and the program is a bit complex. I'm going to see if i can temporarily solve it using some FUSE or bind mount tomfoolery to force-convert files to UTF-8 on write.

**Comment by PQCraft** [comment]
I hit infinite roadblocks and could not figure out any solution to intercept and re-encode the files other than making my own FUSE program.
![](https://media.tenor.com/Ip6aQUKKy_4AAAAM/life-is-roblox-roblox.gif)

**Comment by StrawberryMaster** [comment]
Odd, I'll take a look at this

**Comment by StrawberryMaster** [comment]
It should be working now! Tested this here and I can download it. We weren't properly parsing HTML4-like tags and tried to force UTF-8 encoding on a Windows-1252 file, which didn't go so well

**Comment by skacurt** [comment]
🙋🏻 

What if I told you this issue is still valid? 

Environment:

```
~$ ruby -v
ruby 3.4.3 (2025-04-14 revision d0b7e5b6a0) +PRISM [x86_64-linux]
~$ wayback_machine_downloader --version
2.4.7
```

Command to reproduce:

`wayback_machine_downloader https://bobiler.org --snapshot-at 20050830193805 --recursive-subdomains --subdomain-depth 1 --local`

The HTML response will be encoded in Windows-1254 (Turkish) in this very specific example.

I'd love to get my hands dirty and help, but I don't know Ruby at all.

Anyways, here's the output:

```
Downloading https://bobiler.org to /home/skacurt/wmd-#25/websites/bobiler.org from Wayback Machine archives.
Getting snapshot pages from Wayback Machine API...
. found 5 snapshots.
Saved snapshot list to /home/skacurt/wmd-#25/websites/bobiler.org/.cdx.json

1 files found matching criteria.
1 files to download.

Processing downloads:
[FAILED]  http://www.bobiler.org:80/ # invalid byte sequence in UTF-8 (1/1)

Download finished in 58.25s.
Starting subdomain processing...
Scanning 1 downloaded files for subdomain links...
Error scanning file /home/skacurt/wmd-#25/websites/bobiler.org/index.html: invalid byte sequence in UTF-8
No subdomains found in downloaded content.
Subdomain processing finished in 0.01s.
Results saved in /home/skacurt/wmd-#25/websites/bobiler.org
Cleaning up state files...
```

**Comment by StrawberryMaster** [comment]
@skacurt It seems this issue has been fixed already, I tested it out here and it seems fine. I just forgot to push the latest version of the gem, which I will do right now lol
